### ISSUE TITLE
Download fails if / in filename

### ISSUE THREAD

**Issue by xorbital** [Purkinjee/MonstercatDownloader#3]
Thank you for this great program :)
Since I want to download the catalog for personal listening, I've added `--creatorunfriendly` to the options when running, however at some point the script fails:
```
Traceback (most recent call last):
  File "/home/xorbital/MonstercatDownloader/MonstercatDownloader.py", line 119, in <module>
    DownloadMonstercatLibrary(args.sid, args.directory, args.format, creator_friendly=creator_friendly)
  File "/home/xorbital/MonstercatDownloader/MonstercatDownloader.py", line 86, in DownloadMonstercatLibrary
    with open(full_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xorbital/Monstercat/Singles/Vintage & Morelli x Arielle Maren w/ RNX - Lonely Shore.mp3'
```
Seems like the `Arielle Maren w/ RNX` gets interpreted as a subdirectory :thinking: 
Happens on Manjaro/Arch Linux, Python 3.9.2

**Comment by Purkinjee** [comment]
Thank you for the feedback!

Should be fixed in 81180240b64e807daa4371ab58dbbc64def8b5fe release [v0.4](https://github.com/Purkinjee/MonstercatDownloader/releases/tag/0.4)
